### ISSUE TITLE
Error in upgrading from 1.0.8 to 2.2.0   

### ISSUE THREAD

**Issue by wzymaster** [softlayer/softlayer-ruby#54]
I was using 1.0.8 gem for my rails app, however I found that API calls are breaking after upgrade from 1.0.8 to 2.2.0 gem.

My existing codes look like below :

@softlayer_product_package = SoftLayer::Service.new("SoftLayer_Product_Package",
-                                                             username:  @sl_user_name,
-                                                             api_key:   @sl_api_key)
  package = @softlayer_product_package.object_with_id 46
  available_disks = package.getAvailableStorageUnits
  all_categories  = package.object_mask("itemCategory","isRequired").getConfiguration
  item_prices     = package.object_mask("id", "item.description", "categories.id", "isRequired").getItemPrices

In order to accommodate 2.2.0, I have updated codes to 

@client |= SoftLayer::Client.new(
                 username:   @sl_user_name,  # enter your username here
                  api_key:    @sl_api_key     # enter your api key here
       )
package = SoftLayer::ProductPackage.virtual_server_package(@client)
**available_disks = package.getAvailableStorageUnits
all_categories  = package.object_mask("itemCategory","isRequired").getConfiguration
item_prices     = package.object_mask("id", "item.description", "categories.id", "isRequired").getItemPrices**

but I got errors like below :

**NoMethodError: undefined method `getAvailableStorageUnits' for #SoftLayer::ProductPackage:0x007fe4d497fdb8**

**NoMethodError: undefined method `object_mask' for #SoftLayer::ProductPackage:0x007fe4d4b77e40**

Can you provide some examples on how I can upgrade my rails app to accommodate 2.2.0 here ?
